- name: Ansible and Active Directory
  hosts: Windows
  vars_prompt:
    - name: username
      prompt: Username
      private: false
    - name: firstname
      prompt: Firstname
      private: false
    - name: surname
      prompt: Surname
      private: false
    - name: password
      prompt: Password
      private: true
    - name: DomainUser
      prompt: DomianUsername (domain\user)
      private: false
    - name: DomainUserPass
      prompt: DomainUserPassword
      private: true
 tasks:
   - name: Creating a Domian User
     win_domain_user:
       name: "{{Username}}"
       firstname: "{{firstname}}"
       surname: "{{surname}}"
       password: "{{password}}"
       state: present
       domain_username: "{{DomainUser}}"
       domain_password: "{{DomainUserPass}}"
       domain_server: apt.local
