- name: Creating a Linux User
  hosts: Unbuntu
  become: true
  vars_prompt:
    - name: username
      prompt: Username
      private: false
    - name: password
      prompt: Password
      private: true
      encrypt: sha512_crypt
      confirm: true
      salt_size: 7
  tasks:
    - user: name ={{username}} password={{password}} shell="/bin/bash"
   
